config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  namespace :dashboard do
    root "reviews#index"
    resources :reviews, :cards
    resources :decks do
      put "set_current", on: :member
    end
    resources :user_sessions, only: [:destroy]
    resources :profiles, only: [:edit, :update, :show, :destroy]
    delete "/logout" => "user_sessions#destroy", :as => "logout"
    # profiles
    get "/users" => "profiles#index", :as => "users"
  end

  namespace :home do
    root "user_sessions#new"
    resources :user_sessions, only: [:new, :create]
    resources :registrations, only: [:new, :create]
    # registrations
    get "/signup" => "registrations#new", :as => "signup"

    # sessions
    get "/login" => "user_sessions#new", :as => "login"

    # oauth
    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck

  validate :original_not_equal_translated
  validates :review_date, :deck, presence: true
  validates :original_text, :translated_text, presence: true,
                                              length: { minimum: 2 },
                                              format: { with: /\A[A-ZА-Я]+[a-zа-я]+\z/,
                                                        message: I18n.t('model.big_words') }

  has_attached_file :picture, storage: :dropbox,
                              dropbox_credentials: { app_key: ENV['DROPBOX_APP_KEY'],
                                                     app_secret: ENV['DROPBOX_APP_SECRET'],
                                                     access_token: ENV['DROPBOX_ACCESS_TOKEN'],
                                                     access_token_secret: ENV['DROPBOX_ACCESS_TOKEN_SECRET'],
                                                     user_id: ENV['DROPBOX_USER_ID'],
                                                     access_type: 'app_folder' },
                              styles: { medium: '300x300>', thumb: '100x100>' },
                              default_url: '/images/:style/missing.png',
                              path: "/:class/:attachment/:id_partition/:style/:filename"

  validates_attachment :picture, content_type: { content_type: 'image/jpeg' },
                                 size: { in: 0..1.megabytes }

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  after_initialize :set_date_after_review, if: :new_record?

  scope :expired, -> { where('review_date <= ?', DateTime.now) }
  scope :for_review, -> { expired.offset(rand(Card.expired.count)) }

  def check_translation(user_translation, seconds)
    typos = DamerauLevenshtein.distance(prepare_text(original_text),
                                        prepare_text(user_translation))
    update_params = SuperMemo2.repetition(original_text,
                                          typos,
                                          attempt,
                                          seconds,
                                          repetitions,
                                          e_factor)
    success = update_params.delete(:success)
    update_params[:attempt] = 0
    if success || attempt >= 2
      update(update_params)
    elsif attempt < 2
      self.increment!(:attempt)
    end
    { success: success, typos: typos }
  end

  private

  def original_not_equal_translated
    if prepare_text(original_text) == prepare_text(translated_text)
      errors.add(:original_text, I18n.t("model.equal"))
    end
  end

  def prepare_text(string)
    string.to_s.mb_chars.downcase.strip
  end

  def set_date_after_review
    self.review_date = Time.zone.now
  end
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    before_action :require_login
  end
end

app/controllers/dashboard/cards_controller.rb
module Dashboard
  class CardsController < BaseController
    before_action :find_card, only: [:show, :edit, :update, :destroy]
    before_action :create_deck, only: [:create, :update]

    def index
      @cards = current_user.cards
    end

    def show
    end

    def new
      @card = current_user.cards.new
    end

    def edit
    end

    def create
      @card = current_user.cards.new(card_params)
      if @card.save
        redirect_to dashboard_cards_path, notice: t("controller.cards.create")
      else
        render "new"
      end
    end

    def update
      if @card.update(card_params)
        redirect_to dashboard_cards_path, notice: t("controller.cards.update")
      else
        render "edit"
      end
    end

    def destroy
      @card.destroy
      redirect_to dashboard_cards_path, notice: t("controller.cards.destroy")
    end

    private

    def create_deck
      new_deck = deck_params[:title]
      if new_deck.present?
        deck = current_user.decks.create(title: new_deck)
        params[:card][:deck_id] = deck.id
      end
    end

    def deck_params
      params.require(:deck).permit(:title)
    end

    def find_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:original_text,
                                   :translated_text,
                                   :review_date,
                                   :picture,
                                   :deck_id)
    end
  end
end

app/controllers/dashboard/decks_controller.rb
module Dashboard
  class DecksController < BaseController
    before_action :find_deck, only: [:show, :edit, :update, :destroy]

    def index
      @decks = current_user.decks
    end

    def show
      @cards = @deck.cards
    end

    def new
      @deck = current_user.decks.new
    end

    def create
      @deck = current_user.decks.new(deck_params)
      if @deck.save
        redirect_to dashboard_decks_path
      else
        render "new"
      end
    end

    def edit
    end

    def update
      if @deck.update(deck_params)
        redirect_to dashboard_deck_path, notice: t("controller.decks.update")
      else
        render edit_dashboard_deck_path
      end
    end

    def destroy
      @deck.destroy
      redirect_to dashboard_decks_path
    end

    def set_current
      current_user.update_attributes(default_deck_id: params[:id])
      redirect_to dashboard_deck_path, notice: t("controller.decks.set")
    end

    private

    def find_deck
      @deck = current_user.decks.find(params[:id])
    end

    def deck_params
      params.require(:deck).permit(:title)
    end
  end
end

app/controllers/dashboard/profiles_controller.rb
module Dashboard
  class ProfilesController < BaseController
    before_action :find_profile, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      if current_user.update_attributes(user_params)
        redirect_to dashboard_profile_path, notice: t("controller.profiles.update")
      else
        render "edit"
      end
    end

    def destroy
      @user.destroy
      redirect_back_or_to root_url
    end

    private

    def find_profile
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:profile).permit(:name,
                                      :email,
                                      :password,
                                      :password_confirmation,
                                      :locale)
    end
  end
end

app/controllers/dashboard/reviews_controller.rb
module Dashboard
  class ReviewsController < BaseController
    def index
      @card = current_user.cards_for_review
      respond_to do |format|
        format.html
        format.js
      end
    end

    def create
      @card = current_user.cards.find(review_params[:card_id])
      @review = @card.check_translation(review_params[:user_translation],
                                        review_params[:seconds])
      @review[:user_translation] = review_params[:user_translation]
      if @review[:success]
        flash[:notice] = t("controller.reviews.success",
                           original: @card.original_text,
                           translated: @card.translated_text,
                           user_answer: review_params[:user_translation],
                           typos: @review[:typos],
                           next_review: card_time_loc)
      else
        flash[:alert] = t("controller.reviews.fail",
                          next_review: card_time_loc)
      end
      redirect_to root_path
    end

    private

    def review_params
      params.require(:review).permit(:card_id, :user_translation, :seconds)
    end

    def card_time_loc
      @card.review_date.localtime.strftime("%d/%m/%Y %H:%M")
    end
  end
end

app/controllers/dashboard/user_sessions_controller.rb
module Dashboard
  class UserSessionsController < BaseController
    def destroy
      logout
      redirect_to(:home_login, notice: t("controller.user_sess.logout"))
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index; end
end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for [:dashboard, card], html: { class: "form-horizontal" } do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(card.errors.count, "error") %>
        prohibited this card from being saved:
      </h2>
      <ul>
        <% card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <p>
      <%= f.input :original_text, html: { class: "form-control" },
                                  as: :string,
                                  label: t("views.cards.original_text") %>
    </p>
  </div>
  <div class="form-group">
    <p>
      <%= f.input :translated_text, html: { class: "form-control" },
                                    as: :string,
                                    label: t("views.cards.translated_text") %>
    </p>
  </div>
  <div class="form-group">
    <p>
      <%= f.input :deck_id, collection: current_user.decks,
                               label: t("views.cards.select_deck") %>
    </p>
  </div>

  <div class="form-group">
    <p>
      <%= simple_fields_for :deck, html: { class: "form-horizontal" } do |f_deck| %>
        <%= f_deck.input :title, html: { class: "form-control" },
                                 as: :string,
                                 label: t("views.cards.create_deck") %>
      <% end %>
    </p>
  </div>

  <div class="form-group">
    <p>
      <%= f.input :review_date, html: { class: "form-control" }, as: :datetime, order: [:day, :month, :year], discard_year: true, label: t("views.cards.date_review"), default: 3.days.from_now %>
    </p>
  </div>
  <div class="form-group">
    <p>
      <%= f.input :picture, html: { class: "btn btn-default" },
                            as: :file,
                            label: t("views.cards.picture") %>
    </p>
  </div>
  <p class="form-group">
    <%= f.button :submit, t("views.cards.create") %>
  </p>
<% end %>

app/views/dashboard/cards/edit.html.erb
<h1><%= t("views.cards.edit") %></h1>
<%= render "form", card: @card %>

app/views/dashboard/cards/index.html.erb
<h1><%= t("views.cards.list") %></h1>
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th><%= t("views.cards.original_text") %></th>
      <th><%= t("views.cards.translated_text") %></th>
      <th><%= t("views.cards.deck") %></th>
      <th><%= t("views.cards.date_review") %></th>
      <th><%= t("views.cards.repetitions") %></th>
      <th colspan="3"></th>
    </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= link_to card.deck.title, dashboard_deck_path(card.deck) %></td>
      <td><%= card.review_date.localtime.strftime("%d/%m/%Y %H:%M") %></td>
      <td><%= card.repetitions %></td>
      <td><%= link_to t("views.cards.show"), dashboard_card_path(card) %></td>
      <td><%= link_to t("views.cards.edit"), edit_dashboard_card_path(card) %></td>
      <td><%= link_to t("views.cards.delete"), dashboard_card_path(card), method: :delete,
                                                                data: { confirm: I18n.t("views.cards.sure") } %></td>
  <% end %>
  </table>
</div>

app/views/dashboard/cards/new.html.erb
<h1><%= t("views.cards.new") %> </h1>
<%= render "form", card: @card, deck: @deck %>

app/views/dashboard/cards/show.html.erb
<p>
  <strong><%= t("views.cards.original_text") %></strong>
  <%= @card.original_text %>
</p>

<p>
  <strong><%= t("views.cards.translated_text") %></strong>
  <%= @card.translated_text %>
</p>

<p>
  <strong><%= t("views.cards.deck") %></strong>
  <%= @card.deck.title %>
</p>

<p>
  <strong><%= t("views.cards.date_review") %></strong>
  <%= @card.review_date.localtime.strftime("%d/%m/%Y %H:%M") %>
</p>

<p>
  <strong><%= t("views.cards.picture") %></strong>
  <%= image_tag @card.picture.url(:thumb) %>
</p>

<br>
<p>
  <%= link_to t("views.cards.back"), dashboard_cards_path %>
 </p>