config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  namespace :dashboard do
    root "reviews#index"
    resources :reviews, :cards
    resources :decks do
      put "set_current", on: :member
    end
    resources :user_sessions, only: [:destroy]
    resources :profiles, only: [:edit, :update, :show, :destroy]
    delete "/logout" => "user_sessions#destroy", :as => "logout"
    # profiles
    get "/users" => "profiles#index", :as => "users"
  end

  namespace :home do
    root "user_sessions#new"
    resources :user_sessions, only: [:new, :create]
    resources :registrations, only: [:new, :create]
    # registrations
    get "/signup" => "registrations#new", :as => "signup"

    # sessions
    get "/login" => "user_sessions#new", :as => "login"

    # oauth
    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  end
end

app/views/shared/_guest.html.erb
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><%= t("views.user_sessions.enter") %></b> <span class="caret"></span></a>
  <ul id="login-dp" class="dropdown-menu">
    <li>
       <div class="row">
          <div class="col-md-12">
            <%= t("views.user_sessions.login_via") %>
            <div class="social-buttons">
              <a href="<%= home_auth_at_provider_path(provider: :twitter) %>" class="btn btn-tw"><i class="fa fa-twitter"></i> <%= t("views.auth_twitter") %></a>
              <a href="<%= home_auth_at_provider_path(provider: :vk) %>" class="btn btn-fb"><i class="fa fa-vk"></i> <%= t("views.auth_vk") %></a>
            </div>

            <%= t("views.user_sessions.or") %>

            <%= simple_form_for :user, url: home_user_sessions_path do |f| %>
              <div class="filed">
                <%= f.input :email, as: :string,
                                    label: t("views.user_sessions.email"),
                                    input_html: { id: "login_email" } %><br />
              </div>
              <div class="filed">
                <%= f.input :password, label: t("views.user_sessions.password"),
                                       input_html: { id: "login_password" } %><br />
              </div>
              <div class="form-group">
                <%= check_box_tag :remember, params[:remember], false %>
                <%= label_tag t("views.user_sessions.remember") %>
              </div>
              <div class="actions">
                <%=  f.button :submit, t("views.user_sessions.login"), id: "login_button" %>
              </div>
            <% end %>
          </div>
          <div class="bottom text-center">
            New here ? <%= link_to t("views.noauth.signup"), home_signup_path %>
          </div>
       </div>
    </li>
  </ul>
</li>

<!-- <ul class="nav nav-tabs">
  <li><%= link_to t("views.noauth.signup"), home_signup_path %></li>
  <li><%= link_to t("views.noauth.login"), home_login_path %></li>
  <li><%= link_to t("views.auth_github"), home_auth_at_provider_path(provider: :github) %></li>
  <li><%= link_to t("views.auth_twitter"), home_auth_at_provider_path(provider: :twitter) %></li>
  <li><%= link_to t("views.auth_vk"), home_auth_at_provider_path(provider: :vk) %></li>
  <ul class="nav navbar-nav navbar-right">
    <div class="dropdown">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
        <%= t("views.menu.languages.lang") %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to t("views.menu.languages.en"), root_path(locale: :en) %>
        </li>
        <li>
          <%= link_to t("views.menu.languages.ru"), root_path(locale: :ru)%>
        </li>
      </ul>
   </div>
  </ul>
</ul> -->

app/views/shared/_navi.html.erb
<div class="col-md-12 navigation-links">
  <ul class="nav nav-tabs nav-justified">
    <li><%= link_to t("views.cards.add"), new_dashboard_card_path %>
    <li><%= link_to t("views.cards.all"), dashboard_cards_path %>
    <li><%= link_to t("views.decks.add"), new_dashboard_deck_path %>
    <li><%= link_to t("views.decks.all"), dashboard_decks_path %>
    <li><%= link_to t("views.review"), dashboard_reviews_path %>
  </ul>
</div><br/>

app/views/shared/_user.html.erb
<li><span><h4><%= t("views.auth.profile") %><b><%= current_user.name %></b></h4></span></li>
<li><%= link_to t("views.auth.show_profile"), dashboard_profile_path(current_user) %></li>
<li><%= link_to t("views.auth.edit_profile"), edit_dashboard_profile_path(current_user) %></li>
<li><%= link_to t("views.auth.exit"), dashboard_logout_path, method: :delete %></li>