config/routes.rb
Rails.application.routes.draw do

  root "dashboard#index"

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  namespace :dashboard do
    root "reviews#index"
    resources :reviews, :cards
    resources :decks do
      put "set_current", on: :member
    end
    resources :user_sessions, only: [:destroy]
    resources :profiles, only: [:edit, :update, :show, :destroy]
    delete "/logout" => "user_sessions#destroy", :as => "logout"
    # profiles
    get "/users" => "profiles#index", :as => "users"
  end

  namespace :home do
    root "user_sessions#new"
    resources :user_sessions, only: [:new, :create]
    resources :registrations, only: [:new, :create]
    # registrations
    get "/signup" => "registrations#new", :as => "signup"

    # sessions
    get "/login" => "user_sessions#new", :as => "login"

    # oauth
    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  belongs_to :users

  validates :title, presence: true
  validates_associated :users
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    before_action :require_login
  end
end

app/controllers/dashboard/cards_controller.rb
module Dashboard
  class CardsController < BaseController
    before_action :find_card, only: [:show, :edit, :update, :destroy]
    before_action :create_deck, only: [:create, :update]

    def index
      @cards = current_user.cards
    end

    def show
    end

    def new
      @card = current_user.cards.new
    end

    def edit
    end

    def create
      @card = current_user.cards.new(card_params)
      if @card.save
        redirect_to dashboard_cards_path, notice: t("controller.cards.create")
      else
        render "new"
      end
    end

    def update
      if @card.update(card_params)
        redirect_to dashboard_cards_path, notice: t("controller.cards.update")
      else
        render "edit"
      end
    end

    def destroy
      @card.destroy
      redirect_to dashboard_cards_path, notice: t("controller.cards.destroy")
    end

    private

    def create_deck
      new_deck = deck_params[:title]
      if new_deck.present?
        deck = current_user.decks.create(title: new_deck)
        params[:card][:deck_id] = deck.id
      end
    end

    def deck_params
      params.require(:deck).permit(:title)
    end

    def find_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:original_text,
                                   :translated_text,
                                   :review_date,
                                   :picture,
                                   :deck_id)
    end
  end
end

app/controllers/dashboard/decks_controller.rb
module Dashboard
  class DecksController < BaseController
    before_action :find_deck, only: [:show, :edit, :update, :destroy]

    def index
      @decks = current_user.decks
    end

    def show
      @cards = @deck.cards
    end

    def new
      @deck = current_user.decks.new
    end

    def create
      @deck = current_user.decks.new(deck_params)
      if @deck.save
        redirect_to dashboard_decks_path
      else
        render "new"
      end
    end

    def edit
    end

    def update
      if @deck.update(deck_params)
        redirect_to dashboard_deck_path, notice: t("controller.decks.update")
      else
        render edit_dashboard_deck_path
      end
    end

    def destroy
      @deck.destroy
      redirect_to dashboard_decks_path
    end

    def set_current
      current_user.update_attributes(default_deck_id: params[:id])
      redirect_to dashboard_deck_path, notice: t("controller.decks.set")
    end

    private

    def find_deck
      @deck = current_user.decks.find(params[:id])
    end

    def deck_params
      params.require(:deck).permit(:title)
    end
  end
end

app/controllers/dashboard/profiles_controller.rb
module Dashboard
  class ProfilesController < BaseController
    before_action :find_profile, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      if current_user.update_attributes(user_params)
        redirect_to dashboard_profile_path, notice: t("controller.profiles.update")
      else
        render "edit"
      end
    end

    def destroy
      @user.destroy
      redirect_back_or_to root_url
    end

    private

    def find_profile
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:profile).permit(:name,
                                      :email,
                                      :password,
                                      :password_confirmation,
                                      :locale)
    end
  end
end

app/controllers/dashboard/reviews_controller.rb
module Dashboard
  class ReviewsController < BaseController
    def index
      @card = current_user.cards_for_review
      respond_to do |format|
        format.html
        format.js
      end
    end

    def create
      @card = current_user.cards.find(review_params[:card_id])
      @review = @card.check_translation(review_params[:user_translation],
                                        review_params[:seconds])
      @review[:user_translation] = review_params[:user_translation]
      if @review[:success]
        flash[:notice] = t("controller.reviews.success",
                           original: @card.original_text,
                           translated: @card.translated_text,
                           user_answer: review_params[:user_translation],
                           typos: @review[:typos],
                           next_review: card_time_loc)
      else
        flash[:alert] = t("controller.reviews.fail",
                          next_review: card_time_loc)
      end
      redirect_to root_path
    end

    private

    def review_params
      params.require(:review).permit(:card_id, :user_translation, :seconds)
    end

    def card_time_loc
      @card.review_date.localtime.strftime("%d/%m/%Y %H:%M")
    end
  end
end

app/controllers/dashboard/user_sessions_controller.rb
module Dashboard
  class UserSessionsController < BaseController
    def destroy
      logout
      redirect_to(:home_login, notice: t("controller.user_sess.logout"))
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index; end
end

app/views/dashboard/decks/_form.html.erb
<%= simple_form_for [:dashboard, deck], html: { class: "form-horizontal" } do |f| %>
  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(deck.errors.count, "error") %> prohibited
        this deck from being saved:
      </h2>
      <ul>
        <% deck.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <p>
      <%= f.input :title, html: { class: "form-control" }, as: :string, label: t("views.decks.name") %>
    </p>
  </div>
  <p class="form-group">
    <%= f.button :submit, t("views.decks.create") %>
  </p>
<% end %>

app/views/dashboard/decks/edit.html.erb
<h1><%= t("views.decks.edit") %></h1>
<%= render "form", deck: @deck %>

app/views/dashboard/decks/index.html.erb
<h1><%= t("views.decks.list") %></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th colspan="5"><%= t("views.decks.name") %></th>
    </tr>

  <% @decks.each do |deck| %>
    <tr>
      <td><%= deck.title %></td>
      <td><%= link_to t("views.decks.show"), dashboard_deck_path(deck) %></td>
      <td><%= link_to t("views.decks.edit"), edit_dashboard_deck_path(deck) %></td>
      <td><%= link_to t("views.decks.delete"), dashboard_deck_path(deck), method: :delete,
                                                                data: { confirm: t("views.decks.sure") } %></td>
      <td><%= link_to t("views.decks.default"), set_current_dashboard_deck_path(deck), method: :put %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/dashboard/decks/new.html.erb
<h1><%= t("views.decks.new") %></h4>
<%= render "form", deck: @deck %>

app/views/dashboard/decks/show.html.erb
<p>
  <strong><%= t("views.decks.name") %></strong>
  <%= @deck.title %><br />
  <%= link_to t("views.decks.default"), set_current_dashboard_deck_path, method: :put %>
</p><br>
<p>
  <%= link_to t("views.decks.back"), dashboard_decks_path %>
</p>